### ISSUE TITLE
About Tif Processing

### ISSUE THREAD

**Issue by shawwalt** [alexhe101/FAME-Net#6]
I tried to train this model on a data from WorldView-3 with bands' number of 8 and bit depth of 11. But PIL only support multichannel image with bit depth 8. When I transformed the images to 8 bits, I encountered "PIL.UnidentifiedImageError: cannot identify image file".
Could you please instruct me how to solve this problem? I'll appreciate it a lot if you can give me a hand because It really troubled me. Wish you a good day!

**Comment by alexhe101** [comment]
Sorry for the late reply! It seems the image library you're using can only handle 3- or 4-channel images. You might want to try using the tifffile package instead. For example:

```python
import tifffile as tiff
image = tiff.imread(os.path.join(folder_path, path))
```
Alternatively, you can use the rasterio package like this:

```python
import rasterio
import numpy as np

with rasterio.open(file_path) as src:
    bands = src.read([1, 2, 3, 4, 5, ...])  # Specify the bands you need
    rgb_image = bands.astype('float32')
```
